env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: Uy1Nr56jCSg8v3xMJJn2eTNaO3bp87OPBuhKrnKkwwrBHxeEq24D/cvof6c3ddt3XBJrMoIcbo8EF4NGHpeKBCTdvTbu9RL/sc7LiIWPDq4txjaxwkZ4IH8dzuRLzOU+krQOwsIHSAKC0bCVZmdxdroDUsBSFZBjsPgDnTXvx5F2cHXuBTwPW3xA3D/zHyMtkoU8woyIeOlR8H46jIKZxORnqpAVg5Zd+v1IrjZ4/kv0XJ+8tloqMiBnwKLTq57Dhd2bVPfX9JjJDBbMGXgfQkFErdElPJn8xgqKBMixW6EVCaWmHGvolWXoCr60QXw6rl/2fie2DkZYegpf40SBK9+ZQLnjMeagN0R357yv7zwXh0S2g342v8XnSQuSxpP5b0hox/nkIc6z9+70IzgyBbwD9bBzkqPR5XDrq+LcHvePR+7l+X8vN/FGHNjVxKW2pJ+hLQqlzwc1mpyAPPIBZ6eY57Te/gBmwKiQUf/VaycGzGkUc+SbknW6RDyWQtEg8i04gfkmSjG8PDDruqJvzNyIImIis4gEI2Y1D0+W0SOcfBeMjjRJecnZ6BCvMxsSdnKgKtplWJvjSEopsvqmJVdRgCOPmzMwKRMr24gscn+n/qAusjHM0Xcc0SWP5IlZn8wg2owJyJEdT2JLNmlSWJBbDwP6IPxGE726MDqxuq4=

language: c

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      addons:
        homebrew:
          packages:
          - portaudio
      env:
      - CONF=osx-cocoa
    - os: linux
      env:
      - CONF=unix
      addons:
        coverity_scan:
          project:
            name: "1g0rb0hm/drawterm"
            description: "Build submitted via Travis CI"
          notification_email: boehm.igor@gmail.com
          build_command: "make"
          branch_pattern: devel

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-; fi

script:
  - make
